src/Web/EMS.Web/Controllers/AssignmentsController.cs
namespace EMS.Web.Controllers
{
    using System;
    using System.Threading.Tasks;

    using EMS.Common.ErrorMessages;
    using EMS.Data.Models;
    using EMS.Services.Data;
    using EMS.Web.ViewModels.Assignments;
    using EMS.Web.ViewModels.Employees;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    public class AssignmentsController : BaseController
    {
        private readonly IAssignmentsService assignmentsService;
        private readonly ICountsService countsService;
        private readonly UserManager<ApplicationUser> userManager;

        public AssignmentsController(
            IAssignmentsService assignmentsService,
            ICountsService countsService,
            UserManager<ApplicationUser> userManager)
        {
            this.assignmentsService = assignmentsService;
            this.countsService = countsService;
            this.userManager = userManager;
        }

        public IActionResult Create()
        {
            var viewModel = new CreateAssignmentInputModel();
            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateAssignmentInputModel inputModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(inputModel);
            }

            if (this.assignmentsService.CheckIfAssignmentExist(inputModel.Title))
            {
                this.ModelState.AddModelError(string.Empty, AssignmentInputErrorMessages.AssignmentExists);
                return this.View(inputModel);
            }

            if (inputModel.StartDate > inputModel.DueDate)
            {
                this.ModelState.AddModelError(string.Empty, AssignmentInputErrorMessages.DueDateCanNotBeBeforeStartDate);
                return this.View(inputModel);
            }

            var user = await this.userManager.GetUserAsync(this.User);

            try
            {
                await this.assignmentsService.CreateAsync(inputModel, user == null ? null : user.Id);
            }
            catch (Exception ex)
            {
                this.ModelState.AddModelError(string.Empty, ex.Message);
                return this.View(inputModel);
            }

            return this.RedirectToAction(nameof(this.All));
        }

        public IActionResult All(string sortOrder = "startDate", int page = 1)
        {
            if (page <= 0)
            {
                return this.NotFound();
            }

            var itemsPerPage = 3;

            var viewModel = new AssignmentsListViewModel
            {
                ItemsPerPage = itemsPerPage,
                PageNumber = page,
                ItemsCount = this.countsService.GetAssignmentsCount(),
                ControllerName = this.ControllerContext.ActionDescriptor.ControllerName,
                ActionName = this.ControllerContext.ActionDescriptor.ActionName,
                SortOrder = sortOrder,
                Assignments = this.assignmentsService.GetAll<AssignmentInListViewModel>(sortOrder, page, itemsPerPage),
            };

            if (page > viewModel.PagesCount && viewModel.PagesCount > 0)
            {
                return this.NotFound();
            }

            return this.View(viewModel);
        }

        public IActionResult Edit(int id)
        {
            var viewModel = this.assignmentsService.GetById<EditAssignmentInputModel>(id);
            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditAssignmentInputModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            try
            {
                await this.assignmentsService.UpdateAsync(id, model);
            }
            catch (Exception ex)
            {
                this.ModelState.AddModelError(string.Empty, ex.Message);
                return this.View(model);
            }

            return this.RedirectToAction(nameof(this.All));
        }

        public async Task<IActionResult> Delete(int id)
        {
            await this.assignmentsService.DeleteAsync(id);
            return this.RedirectToAction(nameof(this.All));
        }

        public IActionResult AllPending(string sortOrder = "startDate", int page = 1)
        {
            if (page <= 0)
            {
                return this.NotFound();
            }

            var itemsPerPage = 3;

            var viewModel = new AssignmentsListViewModel
            {
                ItemsPerPage = itemsPerPage,
                PageNumber = page,
                ItemsCount = this.countsService.GetPendingAssignments(),
                ControllerName = this.ControllerContext.ActionDescriptor.ControllerName,
                ActionName = this.ControllerContext.ActionDescriptor.ActionName,
                SortOrder = sortOrder,
                Assignments = this.assignmentsService.GetAllPending<AssignmentInListViewModel>(sortOrder, page, itemsPerPage),
            };

            if (page > viewModel.PagesCount && viewModel.PagesCount > 0)
            {
                return this.NotFound();
            }

            return this.View(viewModel);
        }

        public IActionResult AllCompleted(string sortOrder = "startDate", int page = 1)
        {
            if (page <= 0)
            {
                return this.NotFound();
            }

            var itemsPerPage = 3;

            var viewModel = new AssignmentsListViewModel
            {
                ItemsPerPage = itemsPerPage,
                PageNumber = page,
                ItemsCount = this.countsService.GetCompletedAssignments(),
                ControllerName = this.ControllerContext.ActionDescriptor.ControllerName,
                ActionName = this.ControllerContext.ActionDescriptor.ActionName,
                SortOrder = sortOrder,
                Assignments = this.assignmentsService.GetAllCompleted<AssignmentInListViewModel>(sortOrder, page, itemsPerPage),
            };

            if (page > viewModel.PagesCount && viewModel.PagesCount > 0)
            {
                return this.NotFound();
            }

            return this.View(viewModel);
        }
    }
}

src/Web/EMS.Web/Controllers/EmployeesController.cs
namespace EMS.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Threading.Tasks;

    using EMS.Common.ErrorMessages;
    using EMS.Data.Models;
    using EMS.Services.Data;
    using EMS.Web.ViewModels.Assignments;
    using EMS.Web.ViewModels.Employees;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    public class EmployeesController : BaseController
    {
        private readonly IEmployeesService employeesService;
        private readonly ICountsService countsService;
        private readonly IAssignmentsService assignmentsService;
        private readonly UserManager<ApplicationUser> userManager;

        public EmployeesController(
            IEmployeesService employeesService,
            ICountsService countsService,
            IAssignmentsService assignmentsService,
            UserManager<ApplicationUser> userManager)
        {
            this.employeesService = employeesService;
            this.countsService = countsService;
            this.assignmentsService = assignmentsService;
            this.userManager = userManager;
        }

        public IActionResult Create()
        {
            var viewModel = new CreateEmployeeInputModel();
            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateEmployeeInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            if (this.employeesService.CheckIfEmployeeExist(input.FirstName, input.LastName))
            {
                this.ModelState.AddModelError(string.Empty, EmployeeInputErrorMessages.DuplicateNames);
                return this.View(input);
            }

            var user = await this.userManager.GetUserAsync(this.User);

            try
            {
                await this.employeesService.CreateAsync(input, user == null ? null : user.Id);
            }
            catch (Exception ex)
            {
                this.ModelState.AddModelError(string.Empty, ex.Message);
                return this.View(input);
            }

            return this.RedirectToAction(nameof(this.All));
        }

        public IActionResult All(string sortOrder = "ascending", int page = 1)
        {
            if (page <= 0)
            {
                return this.NotFound();
            }

            var itemsPerPage = 6;

            var viewModel = new EmployeesListViewModel
            {
                ItemsPerPage = itemsPerPage,
                PageNumber = page,
                ItemsCount = this.countsService.GetEmployeesCount(),
                ControllerName = this.ControllerContext.ActionDescriptor.ControllerName,
                ActionName = this.ControllerContext.ActionDescriptor.ActionName,
                SortOrder = sortOrder,
                Employees = this.employeesService.GetAll<EmployeeInListViewModel>(sortOrder, page, itemsPerPage),
            };

            if (page > viewModel.PagesCount && viewModel.PagesCount > 0)
            {
                return this.NotFound();
            }

            return this.View(viewModel);
        }

        public IActionResult ById(int id)
        {
            var viewModel = this.employeesService.GetById<SingleEmployeeViewModel>(id);
            viewModel.Assignments = (ICollection<AssignmentsViewModel>)this.assignmentsService.GetAllPendingAssignmentsForDropDown<AssignmentsViewModel>();
            return this.View(viewModel);
        }

        public IActionResult Edit(int id)
        {
            var inputModel = this.employeesService.GetById<EditEmployeeInputModel>(id);
            return this.View(inputModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditEmployeeInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            try
            {
                await this.employeesService.UpdateAsync(id, input);
            }
            catch (Exception ex)
            {
                this.ModelState.AddModelError(string.Empty, ex.Message);
                return this.View(input);
            }

            return this.RedirectToAction(nameof(this.ById), new { id });
        }

        public async Task<IActionResult> Delete(int id)
        {
            await this.employeesService.DeleteAsync(id);

            return this.RedirectToAction(nameof(this.All));
        }

        public IActionResult ByName(string search, string sortOrder = "ascending", int page = 1)
        {
            if (string.IsNullOrWhiteSpace(search))
            {
                this.ViewData["invalidName"] = true;
                return this.View();
            }

            if (page <= 0)
            {
                return this.NotFound();
            }

            search = search.Trim();

            var itemsPerPage = 6;

            var viewModel = new EmployeesListViewModel
            {
                ItemsPerPage = itemsPerPage,
                PageNumber = page,
                ItemsCount = this.countsService.GetEmployeesCountByName(search),
                ControllerName = this.ControllerContext.ActionDescriptor.ControllerName,
                ActionName = this.ControllerContext.ActionDescriptor.ActionName,
                SortOrder = sortOrder,
                Search = search,
                Employees = this.employeesService.GetByName<EmployeeInListViewModel>(search, sortOrder, page, itemsPerPage),
            };

            this.ViewData["name"] = search;

            return this.View(viewModel);
        }

        public async Task<IActionResult> AssignTask(int assignmentId, int employeeId)
        {
            await this.assignmentsService.AssignToEmployee(employeeId, assignmentId);
            var id = employeeId;
            return this.RedirectToAction(nameof(this.ById), new { id });
        }

        public async Task<IActionResult> CompleteTask(int employeeId, int assignmentId)
        {
            await this.assignmentsService.CompleteAssignment(assignmentId);

            var id = employeeId;
            return this.RedirectToAction(nameof(this.ById), new { id });
        }
    }
}

src/Web/EMS.Web/Views/Shared/_AssignmentsListPartial.cshtml
@using EMS.Web.ViewModels.Assignments;
@model AssignmentsListViewModel

<section class="assignments-wrapper mb-3">
    @foreach (var assignment in Model.Assignments)
    {
        <article class="single-assignment-wrapper">
            <ul>
                <li><p class="single-assignment-wrapper-title">Title: <strong>@assignment.Title</strong></p></li>
                <li><p class="single-assignment-wrapper-description">Description: <strong>@assignment.Description</strong></p></li>
                <li><p class="single-assignment-wrapper-startDate">Start Date: <strong>@assignment.StartDate.ToString("dd MMMM yyyy")</strong></p></li>
                <li><p class="single-assignment-wrapper-dueDate">Due Date: <strong>@assignment.DueDate.ToString("dd MMMM yyyy")</strong></p></li>
                @if (assignment.AssignedEmployee == null && assignment.Finished == false)
                {
                    <li><p class="single-assignment-wrapper-employeesCount">Assignee: <strong>Not Assigned to anyone yet</strong></p></li>
                }
                else
                {
                    <li><p class="single-assignment-wrapper-employeesCount">Assignee: <strong>@(assignment.AssignedEmployee == null ? "Not Assigned to anyone yet" : assignment.AssignedEmployee)</strong></p></li>
                    <li><p class="single-assignment-wrapper-status">Status: <strong>@(assignment.Finished == false ? "Pending" : "Finished on " + assignment.CompletedDate.Value.ToString("dd MMMM yyyy"))</strong></p></li>
                }
                <li class="assignment-btns">
                    <a class="btn btn-success" asp-controller="Assignments" asp-action="Edit" asp-route-id="@assignment.Id">Edit</a>
                    <form method="post" asp-controller="Assignments" asp-action="Delete" asp-route-id="@assignment.Id">
                        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#staticBackdrop">Delete</button>
                        <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="staticBackdropLabel">Please confirm</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        Are you sure you want to delete this task?
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                                        <button class="btn btn-danger">Delete</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </li>
            </ul>
        </article>
    }
</section>

src/Web/EMS.Web/Views/Shared/_EmployeesListPartial.cshtml
@using EMS.Web.ViewModels.Employees;
@model EmployeesListViewModel

<section class="employees-wrapper">
    @foreach (var employee in Model.Employees)
    {
        <a class="single-employee-link" asp-action="ById" asp-route-id="@employee.Id">
            <article class="single-employee-wrapper">
                <i class="fas fa-user"></i>
                <ul>
                    <li><p class="single-employee-wrapper-fullname">Names: <strong>@(employee.FullName.Length > 30 ? employee.FullName.Substring(0, 30) + "..." : employee.FullName)</strong></p></li>
                    <li><p class="single-employee-wrapper-email">Email: <strong>@(employee.Email.Length > 30 ? employee.Email.Substring(0, 30) + "..." : employee.Email)</strong></p></li>
                    <li><p class="single-employee-wrapper-phone">Phone Number: <strong>@employee.PhoneNumber</strong></p></li>
                    <li><p class="single-employee-wrapper-birthday">Birthday: <strong>@employee.DateOfBirth.ToString("dddd, dd MMMM yyyy")</strong></p></li>
                    <li><p class="single-employee-wrapper-salary">Monthly Salary: <strong>@(Math.Round(employee.MonthlySalary, 2)) euro</strong></p></li>
                    <li><p class="single-employee-wrapper-finishedTasks">Pending Tasks: <strong>@employee.PendingAssignmentsCount</strong></p></li>
                    <li><p class="single-employee-wrapper-finishedTasks">Completed Tasks: <strong>@employee.FinishedAssignmentsCount</strong></p></li>
                </ul>
            </article>
        </a>
    }
</section>

src/Web/EMS.Web/Views/Shared/_Layout.cshtml
@using EMS.Common
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/fontawesome/css/all.min.css" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://unpkg.com/gijgo@1.9.14/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://unpkg.com/gijgo@1.9.14/css/gijgo.min.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" asp-area="" asp-controller="Employees" asp-action="All">All Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" asp-area="" asp-controller="Employees" asp-action="Create">Add Employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" asp-area="" asp-controller="Assignments" asp-action="All">All Tasks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" asp-area="" asp-controller="Assignments" asp-action="AllPending">Pending Tasks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" asp-area="" asp-controller="Assignments" asp-action="AllCompleted">Completed Tasks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" asp-area="" asp-controller="Assignments" asp-action="Create">Add Task</a>
                        </li>
                    </ul>
                    <form asp-area="" asp-controller="Employees" asp-action="ByName" class="d-flex">
                        <input class="form-control me-2" name="search" type="search" placeholder="Search by Name" aria-label="Search" required>
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    
    <div class="pages-container">
        <main role="main" class="pb-3">
            @this.RenderBody()
        </main>
    </div>
    
    <footer class="navbar-dark bg-dark">
        <a href="https://github.com/DimitarStefan0v/Employee-Management-System" title="Open Source System"><span>&copy; @(DateTime.Now.Year + " - " + GlobalConstants.SystemName) - Open Source System</span></a>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    @await this.RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/Web/EMS.Web/Views/Shared/_PagingPartial.cshtml
@model PagingViewModel

<nav aria-label="..." class="paging">
    <ul class="pagination justify-content-center">
        @if (Model.HasPreviousPage)
        {
            <li class="page-item">
                <a class="page-link" asp-controller="@Model.ControllerName" asp-action="@Model.ActionName" asp-route-search="@Model.Search" asp-route-sortOrder="@Model.SortOrder" asp-route-page="@Model.PreviousPageNumber">Previous</a>
            </li>
        }
        else
        {
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">Previous</a>
            </li>
        }

        @for (int i = this.Model.PageNumber - 3; i < this.Model.PageNumber; i++)
        {
            if (i > 0)
            {
                <li class="page-item">
                    <a class="page-link" asp-controller="@Model.ControllerName" asp-action="@Model.ActionName" asp-route-search="@Model.Search" asp-route-sortOrder="@Model.SortOrder" asp-route-page="@i">@i</a>
                </li>
            }
        }

        <li class="page-item active" aria-current="page">
            <span class="page-link">@Model.PageNumber</span>
        </li>

        @for (int i = this.Model.PageNumber + 1; i < this.Model.PageNumber + 4; i++)
        {
            if (i <= this.Model.PagesCount)
            {
                <li class="page-item">
                    <a class="page-link" asp-controller="@Model.ControllerName" asp-action="@Model.ActionName" asp-route-search="@Model.Search" asp-route-sortOrder="@Model.SortOrder" asp-route-page="@i">@i</a>
                </li>
            }
        }

        @if (Model.HasNextPage)
        {
            <li class="page-item">
                <a class="page-link" asp-controller="@Model.ControllerName" asp-action="@Model.ActionName" asp-route-search="@Model.Search" asp-route-sortOrder="@Model.SortOrder" asp-route-page="@Model.NextPageNumber">Next</a>
            </li>
        }
        else
        {
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">Next</a>
            </li>
        }
    </ul>
</nav>

src/Web/EMS.Web/Views/Shared/_SortingPartial.cshtml
@model PagingViewModel

<section class="sort-wrapper">
    <span>Sort By:</span>
    <ul>
        <li><a class="ascending-sort-link" asp-route-search="@Model.Search" asp-route-sortOrder="ascending" asp-route-id="1">Age<i class="fas fa-long-arrow-alt-up"></i></a></li>
        <li><a class="descending-sort-link" asp-route-search="@Model.Search" asp-route-sortOrder="descending" asp-route-id="1">Age<i class="fas fa-long-arrow-alt-down"></i></a></li>
        <li><a class="completed-tasks-sort-link" asp-route-search="@Model.Search" asp-route-sortOrder="pending-tasks" asp-route-id="1">Pending Tasks</a></li>
        <li><a class="completed-tasks-sort-link" asp-route-search="@Model.Search" asp-route-sortOrder="finished-tasks" asp-route-id="1">Finished Tasks</a></li>
        <li><a class="salary-sort-link" asp-route-search="@Model.Search" asp-route-sortOrder="salary" asp-route-id="1">Salary</a></li>
    </ul>
</section>
<input id="sort-order-value" type="hidden" value="@Model.SortOrder" />